In [1]:
import os
import pandas as pd
import json

In [22]:
# 기본 경로 설정
base_path = "/home/elicer/jm/seg/중소형주차장"
directories = os.listdir(base_path)

In [23]:
# DataFrame 초기화
df = pd.DataFrame(columns=["Parking Space Count", "Driveable Space Count"])

# 모든 노상 폴더 순회
for dir_name in directories:
    dir_path = os.path.join(base_path, dir_name, "label")
    
    if os.path.isdir(dir_path):
        files = os.listdir(dir_path)
        
        # 모든 JSON 파일 순회
        for file_name in files:
            if file_name.endswith(".json"):
                file_path = os.path.join(dir_path, file_name)
                
                # JSON 파일 읽기
                with open(file_path, 'r', encoding='utf-8') as file:
                    data = json.load(file)
                
                # Parking Space와 Driveable Space의 개수를 세는 변수
                parking_space_count = 0
                driveable_space_count = 0
                
                # Segmentation 리스트를 순회하며 각 공간의 이름을 확인
                for segment in data.get('segmentation', []):
                    if segment['name'] == 'Parking Space':
                        parking_space_count += 1
                    elif segment['name'] == 'Driveable Space':
                        driveable_space_count += 1
                
                # 행 이름 설정 (노상 번호와 파일 이름)
                row_name = f"{dir_name}_{file_name}"
                
                # DataFrame에 추가
                df.loc[row_name] = [parking_space_count, driveable_space_count]

In [24]:
df

                          Parking Space Count  Driveable Space Count
중소형주차장_301_00008801.json                    0                      1
중소형주차장_301_00008802.json                    0                      1
중소형주차장_301_00008803.json                    0                      1
중소형주차장_301_00008804.json                    0                      1
중소형주차장_301_00008805.json                    0                      1
...                                       ...                    ...
중소형주차장_467_00000208.json                    0                      1
중소형주차장_467_00000209.json                    2                      1
중소형주차장_467_00000210.json                    2                      1
중소형주차장_467_00000211.json                    1                      1
중소형주차장_467_00000212.json                    1                      1

[32430 rows x 2 columns]

In [25]:
# Parking Space Count가 0인 데이터 이름 리스트
parking_zero_list = df[df['Parking Space Count'] == 0].index.tolist()

# Driveable Space Count가 0인 데이터 이름 리스트
driveable_zero_list = df[df['Driveable Space Count'] == 0].index.tolist()

In [26]:
pd.DataFrame(parking_zero_list)

                              0
0      중소형주차장_301_00008801.json
1      중소형주차장_301_00008802.json
2      중소형주차장_301_00008803.json
3      중소형주차장_301_00008804.json
4      중소형주차장_301_00008805.json
...                         ...
14310  중소형주차장_467_00000204.json
14311  중소형주차장_467_00000205.json
14312  중소형주차장_467_00000206.json
14313  중소형주차장_467_00000207.json
14314  중소형주차장_467_00000208.json

[14315 rows x 1 columns]

In [27]:
pd.DataFrame(driveable_zero_list)

                            0
0    중소형주차장_353_00000151.json
1    중소형주차장_353_00000152.json
2    중소형주차장_353_00000153.json
3    중소형주차장_354_00000445.json
4    중소형주차장_354_00000446.json
..                        ...
139  중소형주차장_465_00000167.json
140  중소형주차장_465_00000168.json
141  중소형주차장_465_00000169.json
142  중소형주차장_465_00000170.json
143  중소형주차장_465_00000171.json

[144 rows x 1 columns]